##########################################################################################
#                              nsq:
# ref:
#   - docs:
#     - https://nsq.io/deployment/docker.html
#   - image:
#     - https://registry.hub.docker.com/r/nsqio/nsq/
#   - 本地浏览器访问:
#       - http://127.0.0.1:4171
##########################################################################################

version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd
    ports:
      - 14160:4160
      - 14161:4161  # 服务端口

  # data node:
  nsqd1:
    image: nsqio/nsq
    container_name: nsqd1
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150
      - 4151

  # data node:
  nsqd2:
    image: nsqio/nsq
    container_name: nsqd2
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150
      - 4151


  # admin ui:
  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - 14171:4171


##########################################################################################
#                                 自定义依赖:
##########################################################################################


# 自定义数据卷:
volumes:
  #
  nsqd1_data:
  nsqd2_data:



